### ISSUE TITLE
Your dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [jieunparklee/covid19-unemployment#1]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/MCFZ43.

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by jieunparklee** [comment]
Hi, thank you for your interest in my project. The dataset is pulled from [U.S. Bureau of Labor Statistics](https://www.bls.gov). 
Unfortunately I do not plan to keep the dataset on this repository up-to-date, however I have implemented a function _data_update_ that will update the dataset when new data points are available. 
Please refer to the README for more details. Thank you.

**Comment by k-goncharova** [comment]
Thank you
